package GUI_Package;


import Mediator.Mediator;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alex
 */
public class ServiceListGUI extends javax.swing.JFrame {

    private String username;
    private String typeName;
    private ServTableModel tableModel;
    private Mediator med;
    /**
     * Creates new form GUI
     */
    public ServiceListGUI(Mediator med, String username, String password) {
        this.username = new String(username);
        this.med = med;
        initComponents();
        //config();
        configTable();
    }
    void configTable() {

        tableModel = new ServTableModel(med, jTable1, username);
        
        jTable1.setModel(tableModel);
        jTable1.getColumnModel().getColumn(0).setCellRenderer(new ServTableCellRender());        
        jTable1.getColumnModel().getColumn(0).setCellEditor(new ServTableEditor() );
        
        jTable1.getColumnModel().getColumn(1).setCellRenderer(new UsersTableCellRender());
        jTable1.getColumnModel().getColumn(1).setCellEditor(new UsersTableEditor() );
        
        jTable1.getColumnModel().getColumn(2).setCellRenderer(new StateTableCellRender());
        jTable1.getColumnModel().getColumn(2).setCellEditor(new StateTableEditor());
        
        jTable1.getColumnModel().getColumn(3).setCellRenderer(new ProgressTableCellRender());
        jTable1.getColumnModel().getColumn(3).setCellEditor(new ProgressTableEditor());
        readConfigFile();
    }
    void readConfigFile() {
        Vector vct = new Vector();

        try {
            
            BufferedReader br = new BufferedReader(new FileReader(username));
            this.typeName = br.readLine();
            jLabel1.setText(typeName);
            String line;
            while(true) {
               line = br.readLine();
               if(line == null)
                   break;
               if(typeName.compareTo("Producator") == 0) {
                   ProdServListModel prod = new ProdServListModel(line, med);
                   tableModel.addRow(prod);
                   ArrayList<String> message = med.sendOfferService(username, line);
                   tableModel.addNewUsers(message, line);
               }
               else {
                   ConServListModel con = new ConServListModel(line, med);
                   tableModel.addRow(con);
               }
                   
            }
            med.startWebServiceListener();
            
        }
        catch(Exception e) {
            e.printStackTrace();
        }
    }
    void config() {
        try {
            BufferedReader br = new BufferedReader(new FileReader("config.txt"));
            username = br.readLine();
            typeName = br.readLine();
            if(username == null || typeName == null) {
                //  TODO display an error message.
            }
            setUsername(username);
        }
        catch(Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Username");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable1FocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Log out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTable1FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(med.logout()) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    void setUsername (String username) {
        jLabel1.setText(username);
    }
    
    public void updateTable() {
        tableModel.fireTableDataChanged();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
